before_install:
  - sudo apt-get update -q
  - sudo apt-get install -q postgresql-9.1-postgis
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis

env:
  - NPROCS=1 JOBS=1

language: node_js
node_js:
  - "0.8"
