before_script:
  - sudo apt-get install -q gdal-bin
  - sudo apt-add-repository --yes ppa:cartodb/postgresql-9.3
  - sudo apt-add-repository --yes ppa:cartodb/gis
  - sudo apt-get update
  - sudo apt-get install -q postgresql-9.3-postgis-2.1
  - psql -c 'create database template_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d template_postgis
  - ./configure

language: node_js
node_js:
  - "0.8"
  - "0.10"
