before_install:
  - psql -c 'create database template_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d template_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d template_postgis
  - ./configure

language: node_js
node_js:
  - "0.8"
  - "0.10"
